### ISSUE TITLE
Circular References

### ISSUE THREAD

**Issue by jamesgraves** [jamesgraves/bonzAI#3]
When building with the `gulp compile-flattened` task which generates the individual javascript files, the resultant system fails to run:

    Error: Circular reference to module 'helpers.loopHelper'
        at ai.operations.Operation:4:22
        at ContextifyScript.Script.runInContext (vm.js:35:29)
        at ai.operations.FortOperation:3:21

This does not happen with the `gulp compile-bundled` target which combines the output into a single main.js file.

**Comment by bonzaiferroni** [comment]
yeah this ought to be fixed, I was surprised that webstorm let me do a circular reference.

loopHelper needs a reference to operations because that is where they are instantiated. But each operation class also has a reference to loophelper because that is where I was declaring an instance of empire and assigning to global (so that it is my "top level object"). I should probably think of a better way to do that

**Comment by jamesgraves** [comment]
Fixed with: bonzaiferroni/bonzAI@670c5774094b9e6dde02f3140040f2b0aadbf624
